version: '3.8'
services:
  banking-core:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/banking_core
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root        # REQUIRED
      MYSQL_DATABASE: banking_core     # auto-create DB
    ports:
      - "3307:3306"
    restart: always