name: Deploy Spring boot application to aws ec2 machine
on:
  push:
    branches:
      - Master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PASSWORD }}
          port: 22

          script: |
            cd banking-application/banking-core/
            
            git pull origin master
            
            docker compose down
            
            docker compose up -d --build
            
            docker image prune -f
